config/routes.rb
RailsIds::Engine.routes.draw do
  resource :dashboard, only: [:show]

  resources :attacks, only: [:index, :show]
  resources :events, only: [:index, :show] do
    member do
      get 'verify', as: 'verify', action: 'verify'
      get 'deny', as: 'deny', action: 'deny'
    end
  end
  resources :machine_learning_examples, only: [:index, :new, :create, :edit, :update] do
    collection do
      get 'import', as: 'new_import', action: 'new_import'
      post 'import'
    end
  end

  root 'dashboard#show'
end

app/models/rails_ids/attack.rb
module RailsIds
  ##
  # Attack model in the RailsIds-Gem.
  # Logs all attacks, detected by analyzing events.
  #
  class Attack < ActiveRecord::Base
    RESPONSES = %w(none logout lock_user lock_page).freeze

    # Relations
    has_many :events
  end
end

app/models/rails_ids/event.rb
module RailsIds
  ##
  # Event model in the RailsIds-Gem.
  # Logs all events that where relevant for detecting an attack.
  #
  # An event is of a type, that describes what an user was doing,
  # and a weight, to be used by the response module, to know how to react.
  #
  class Event < ActiveRecord::Base
    TYPES = %w(INSUFFICIANT_AUTHORIZATION LOGIN SQL_INJECTION XSS
               UNPRINTABLE_CHAR CSRF_TOKEN FILE_ACCESS SESSION
               AUTOMATICALLY_RECOGNIZED).freeze
    WEIGHT = %w(unsuspicious suspicious attack).freeze

    # Relations
    belongs_to :user, class_name: RailsIds.user_class
    belongs_to :attack

    # Validations
    validates :event_type, presence: true, inclusion: { in: TYPES, message: '%{value} is not a valid type' }
    validates :weight, presence: true, inclusion: { in: WEIGHT, message: '%{value} is not a valid weight' }

    # Scopes
    scope :in_time, -> (timeout) { where('created_at > ?', Time.zone.now - timeout) }
    scope :verified, -> { where(verified: true) }
  end
end

app/models/rails_ids/machine_learning_example.rb
module RailsIds
  ##
  #
  #
  class MachineLearningExample < ActiveRecord::Base
    STATUS = %w(active inactive).freeze

    validates :status, inclusion: { in: STATUS, message: '%{value} is not a valid status' }
  end
end

app/models/rails_ids/machine_learning_result.rb
module RailsIds
  ##
  #
  #
  class MachineLearningResult < ActiveRecord::Base
    STATUS = %w(old new active).freeze

    validates :status, inclusion: { in: STATUS, message: '%{value} is not a valid status' }
  end
end

app/models/rails_ids/machine_learning_token.rb
module RailsIds
  ##
  #
  #
  class MachineLearningToken < ActiveRecord::Base
    validates :token, presence: true
  end
end

app/controllers/rails_ids/application_controller.rb
module RailsIds
  class ApplicationController < ActionController::Base
  end
end

app/controllers/rails_ids/attacks_controller.rb
require_dependency 'rails_ids/application_controller'

module RailsIds
  ##
  # Showing an overview of attacks, that result from events.
  # Get more information about a single attack.
  #
  class AttacksController < ApplicationController
    before_action :load_attack, only: [:show]

    def index
      @attacks = Attack.all
    end

    def show
    end

    private

    def load_attack
      @attack = Attack.find(params[:id])
    end
  end
end

app/controllers/rails_ids/dashboard_controller.rb
require_dependency 'rails_ids/application_controller'

module RailsIds
  ##
  # Dashboard that displays an information summary
  #
  class DashboardController < ApplicationController
    def show
      @attacks = Attack.all
      @events  = Event.all
    end
  end
end

app/controllers/rails_ids/events_controller.rb
require_dependency 'rails_ids/application_controller'

module RailsIds
  ##
  # Showing an overview of events, that are recognized by the detection module.
  # Read log and more information about a single event.
  #
  class EventsController < ApplicationController
    before_action :load_event, only: [:show, :verify, :deny]

    def index
      @events = Event.all
    end

    def show
    end

    def verify
      if @event.sensor == 'BlacklistInputValidation'
        MachineLearningExample.create!(text: @event.match, classifier: 0, status: 'active')
      end
      @event.update(verified: true)
      redirect_to :back
    end

    def deny
      if @event.sensor == 'BlacklistInputValidation'
        MachineLearningExample.create!(text: @event.match, classifier: 0, status: 'active')
      end
      @event.destroy!
      redirect_to :back
    end

    private

    def load_event
      @event = Event.find(params[:id])
    end
  end
end

app/controllers/rails_ids/machine_learning_examples_controller.rb
require_dependency 'rails_ids/application_controller'

module RailsIds
  ##
  # Showing an overview of events, that are recognized by the detection module.
  # Read log and more information about a single event.
  #
  class MachineLearningExamplesController < ApplicationController
    before_action :load_example, only: [:edit, :update]

    def index
      @examples = MachineLearningExample.all
    end

    def new
      @example = MachineLearningExample.new
    end

    def create
      @example = MachineLearningExample.new(example_params)
      if @example.save
        flash[:notice] = t('.success')
        redirect_to machine_learning_examples_path
      else
        flash[:notice] = t('.failure')
        render :new
      end
    end

    def edit
    end

    def update
      if @example.update(example_params)
        flash[:notice] = t('.success')
        redirect_to machine_learning_examples_path
      else
        flash[:notice] = t('.failure')
        render :edit
      end
    end

    def new_import
    end

    def import
      require 'csv'
      csv = CSV.parse(params[:import], headers: false)
      csv.each do |row|
        row = row.to_a
        MachineLearningExample.create!(classifier: row[0], text: row[1], status: 'active')
      end
      redirect_to machine_learning_examples_path
    end

    private

    def load_example
      @example = MachineLearningExample.find(params[:id])
    end

    def example_params
      params.require(:machine_learning_example).permit(:text, :classifier, :status)
    end
  end
end

app/views/layouts/rails_ids/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsIds</title>
  <%= stylesheet_link_tag    "rails_ids/application", media: "all" %>
  <%= javascript_include_tag "rails_ids/application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/rails_ids/attacks/index.html.erb
<h1><%= t('.attacks') %></h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @attacks.each do |attack| %>
      <tr>
        <td><%= attack.id %></td>
        <td><%= link_to '->', rails_ids.attack_path(attack) %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/rails_ids/attacks/show.html.erb
<h1>Attack <%= @attack.id %></h1>

<%= link_to 'Back', rails_ids.attacks_path %>

app/views/rails_ids/dashboard/show.html.erb
<h1><%= t('.dashboard') %></h1>

<p>Events last hour: <%= @events.where('created_at > ?', Time.zone.now - 1.hour).count %></p>
<p>Attacks last hour: <%= @attacks.where('created_at > ?', Time.zone.now - 1.hour).count %></p>

<p>Events today: <%= @events.where('created_at > ?', Time.zone.now.beginning_of_day).count %></p>
<p>Attacks today: <%= @attacks.where('created_at > ?', Time.zone.now.beginning_of_day).count %></p>

<hr />
<p>Events total: <%= @events.count %></p>
<p>Attacks total: <%= @attacks.count %></p>

<hr />
<p>Want to check out the events? Go to the <%= link_to 'Events page', events_path %></p>
<p>Or do you want to see recognized attacks? Go to the <%= link_to 'Attacks page', attacks_path %></p>
<p>Using the machine learning sensor? Check out the <%= link_to 'Examples', machine_learning_examples_path %> the algorithms are based on</p>

app/views/rails_ids/events/index.html.erb
<h1><%= t('.events') %></h1>

<table>
  <thead>
    <tr>
      <th>ID</th>
      <th>TYPE</th>
      <th>DATE</th>
      <th></th>
      <th>Correct?</th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.id %></td>
        <td><%= event.event_type %></td>
        <td><%= event.created_at %></td>
        <td><%= link_to '->', rails_ids.event_path(event) %></td>
        <td>
          <% unless event.verified? %>
            <%= link_to 'Yes', rails_ids.verifiy_event_path(event) %> |
            <%= link_to 'No', rails_ids.deny_event_path(event) %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/rails_ids/events/show.html.erb
<h1>Event <%= @event.id %></h1>

<p><%= @event.event_type %></p>
<p><%= @event.log %></p>

<%= link_to 'Back', rails_ids.events_path %>

app/views/rails_ids/machine_learning_examples/_form.html.erb
<%= simple_form_for :example do |f| %>
  <%= f.input :text %>
  <%= f.input :classifier, collection: { 0 => 'attack', 1 => 'friendly' } %>
  <%= f.input :status, collection: MachineLearningExample::STATUS %>
  <%= f.submit %>
<% end %>

app/views/rails_ids/machine_learning_examples/edit.html.erb
<h1><%= t('.edit_example') %></h1>

<%= render 'form' %>

app/views/rails_ids/machine_learning_examples/index.html.erb
<h1><%= t('.examples') %></h1>

<%= link_to 'Import', new_import_machine_learning_examples_path %>
<%= link_to 'New', new_machine_learning_example_path %>

<table class="table">
  <thead>
    <tr>
      <th>ID</th>
      <th>TEXT</th>
      <th>CLASSIFIER</th>
      <th>STATUS</th>
      <th>DATE</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @examples.each do |example| %>
      <tr>
        <td><%= example.id %></td>
        <td><%= example.text %></td>
        <td><%= example.classifier %></td>
        <td><%= example.status %></td>
        <td><%= example.created_at %></td>
        <td><%= link_to '->', rails_ids.edit_machine_learning_example_path(example) %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/rails_ids/machine_learning_examples/new.html.erb
<h1><%= t('.new_example') %></h1>

<%= render 'form' %>

app/views/rails_ids/machine_learning_examples/new_import.erb
<h1><%= t('.new_import') %></h1>

<%= form_tag import_machine_learning_examples_path, method: "post" do %>
  <%= label_tag(:import, "Content:") %>
  <%= text_area_tag(:import) %>
  <%= submit_tag("Import") %>
<% end %>